# CHANGED_BY_AI: 2026-03-05 - Use static frameworks for Firebase pod compatibility
require Pod::Executable.execute_command('node', [
  '-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__
]).strip

platform :ios, '15.1'
prepare_react_native_project!

ENV['RCT_NEW_ARCH_ENABLED'] = '0'
$RNFirebaseAsStaticFramework = true
use_frameworks! :linkage => :static

target 'Spendly' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
