<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Spendly.Shared.Core\Spendly.Shared.Core.csproj" />
      <ProjectReference Include="..\Spendly.Shared.DataLayer\Spendly.Shared.DataLayer.csproj" />
      <ProjectReference Include="..\Spendly.Shared.ViewModels\Spendly.Shared.ViewModels.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.3" />
    </ItemGroup>

</Project>
